* Pentest Environment Deployment

This tool provide an easy way to deploy a clean pentesting environment with Kali linux using vagrant and virtualbox.

** Requirements
I assume you are familiar with virtualbox and vagrant.
- https://www.virtualbox.org/
- http://www.vagrantup.com/

Tested with:
- Virtualbox (4.2.16)
- Vagrant (1.2.7)

*** Vagrant plugins
- vagrant-berkshelf (for targets deployment)

** About boxes
*** Boxes URL
- Kali linux 1.0: http://ftp.sliim-projects.eu/boxes/kali-linux-1.0-amd64.box
  + VirtualBox 4.2.10
  + Vagrant 1.0.7
- Kali linux 1.0.4: http://ftp.sliim-projects.eu/boxes/kali-linux-1.0.4-amd64.box
  + VirtualBox 4.2.16
  + Vagrant 1.2.7
*** Changes details
Provided boxes are fresh install of Kali linux with some changes:

**** Kali linux 1.0
 - Installation of linux kernel headers for vbox guest additions.
 - Installation of virtualbox guest additions.
 - Installation of ~chef~ package for provisioning.
 - ~vagrant~ user was created for provisionning (Password: ~tnargav~).
 - ~admin~ group don't require password for sudo.
 - ~vagrant~ user is in ~admin~ group.
 - Authorized keys for ~vagrant~ user are stored in ~ssh-keys/~ directory (no passphrase).
 - Enabling rpcbind, nfs-common and ssh services at boot.

**** Kali linux 1.0.4
Fresh install from http://cdimage.kali.org/kali-latest/amd64/kali-linux-1.0.4-amd64-mini.iso

 - Installation of linux kernel headers for vbox guest additions.
 - Installation of virtualbox guest additions.
 - Installation of ~chef~ package for provisioning.
 - Authorized keys for ~root~ user are stored in ~ssh-keys/~ directory (no passphrase).
 - Enabling rpcbind, nfs-common and ssh services at boot.
 - Modified /etc/issue for vagrant os detection.
 - MAC address for private network was added in /etc/NetworkManager/NetworkManager.conf to disable auto connect.

*Please don't forget to read security warning below !*

** Installation
*** Vagrant plugins
#+BEGIN_SRC shell
vagrant plugin install vagrant-berkshelf
#+END_SRC
*** Pentest-env
#+BEGIN_SRC shell
git clone https://github.com/Sliim/pentest-env.git
cd pentest-env
vagrant up kali
#+END_SRC

** Usage
*** Running Kali linux 1.0
#+BEGIN_SRC shell
vagrant up kali
#+END_SRC
*** Targets deployment
You can easily deploy targets with your kali instance.

To setup targets, edit ~custom/targets~ (create if not exists) and set one target per line you want to deploy.

#+BEGIN_SRC ruby
$ cat custom/targets
gruyere
vicnum
#+END_SRC

Here two virtual machines will be deployed with a gruyere and a vicnum instance ready to use.

To deploy Kali linux and targets:
#+BEGIN_SRC shell
vagrant up
#+END_SRC

Available targets are:
- ~dvwa~ - DVWA (Damn Vulnerable Web Application) - http://www.dvwa.co.uk/
- ~vicnum~ - OWASP Vicnum - https://www.owasp.org/index.php/Category:OWASP_Vicnum_Project
- ~gruyere~ - Google Gruyere - http://google-gruyere.appspot.com/
- ~bricks~ - OWASP Bricks - https://www.owasp.org/index.php/OWASP_Bricks

** Known issues
*** Hostonly on kali linux 1.0 fail
Hostonly connection will be reset at first vm creation.
To resolve this, disconnect connection in gui mode and run in your vagrant directory:
#+BEGIN_SRC shell
vagrant reload kali
#+END_SRC
** Security warning
*** Kali linux 1.0
Virtual machine boot with sshd service running and may cause some security issues:
  - Bridged network is enabled by default.
  - Default root password of this box is insecure (toor).
  - Vagrant user is insecure
    + Private key stored in ~ssh-keys/~.
    + Password known (~tnargav~).
    + User in sudoers with no password required.

*** Kali linux 1.0.4
Virtual machine boot with sshd service running and may cause some security issues:
  - Bridged network is enabled by default.
  - Default root password of this box is insecure (toor).

** License
   See COPYING file
