* Pentest Environment Deployer

This repo provides an easy way to deploy a clean pentesting environment with Kali linux using vagrant and virtualbox.

** Requirements
I assume you are familiar with virtualbox and vagrant.
- https://www.virtualbox.org/
- http://www.vagrantup.com/

Latest ~pentest-env~ release is tested with:
- Virtualbox (5.0.14)
- Vagrant (1.8.1)

** Current box
*** Kali 2016.1
- http://box.hackbbs.org/kali-2016.1.box

See the [[https://github.com/Sliim/pentest-env/wiki/About-boxes][wiki]] page about boxes for more details.

** Getting started
To get started with ~pentest-env~, clone this repository and run ~vagrant up kali~ inside the directory.
This will download and run the Kali instance.

You can customize, add targets, create new targets etc.. inside ~pentest-env~

For more details, visit the [[https://github.com/Sliim/pentest-env/wiki][wiki]] page.

If you use ~Chef~, this [[https://github.com/Sliim/pentest-chef-repo][chef-repo]] is for you!

** About Security
Provided boxes run the ~sshd~ service.

So if you plan to run the Kali linux with a Bridged interface, default setup can be dangerous!

- ~root~ password of kali is ~toor~.
- SSH private key is not private! Anyone can use this [[https://github.com/Sliim/pentest-env/blob/master/ssh-keys/pentest-env][key]] to connect to your instance.
- The Kali linux 1.0 box added a ~vagrant~ user with password ~tnargav~ and is in sudoers with no password required.

** License
   See COPYING file
