* Pentest Environment Deployer

This repo provides an easy way to deploy a clean pentesting environment with Kali linux using vagrant and virtualbox.

** Requirements
I assume you are familiar with virtualbox and vagrant.
- https://www.virtualbox.org/
- http://www.vagrantup.com/

Latest ~pentest-env~ release is tested with:
- Virtualbox (5.0.24)
- Vagrant (1.8.5)

** Current box
*** Kali 2016.2
| Box               | SHA256                                                           |
|-------------------+------------------------------------------------------------------|
| [[http://box.hackbbs.org/kali-2016.2.box][Kali 2016.2]]       | 4c04e28c4fb7b6601cb838fba753af4cffb3ea2f0a9aa4c13f834cabd7e353cb |
| [[http://box.hackbbs.org/kali-2016.2-light.box][Kali 2016.2-light]] | 5d455bf1cf8d7b2b4f3be7c4b3cc43152ae5cfe09eaf4aaf30ac112aa6bd3b40 |
| [[http://box.hackbbs.org/kali-2016.2-lxde.box][Kali 2016.2-lxde]]  | d7d534c329d43b6df9b294eeb558f8346b20d9334ef037f4c0360ed2acfeaab6 |
| [[http://box.hackbbs.org/kali-2016.2-xfce.box][Kali 2016.2-xfce]]  | 5342e85587b64fc0fd58b54a07fd97264040ec3027106807b434bd6fbb80b7b6 |
| [[http://box.hackbbs.org/kali-2016.2-mate.box][Kali 2016.2-mate]]  | f8a18c0a3f0cd6ed8c689dfebb04fc8d2a0018dc38effc1e67372787d9aa67b3 |
| [[http://box.hackbbs.org/kali-2016.2-e17.box][Kali 2016.2-e17]]   | f5c06a16a34982fd107c0fce9ee42f3fe31d42636a7a551e08f4dc4dd7f275da |


See the [[docs/About-boxes.md][documentation]] page about boxes for more details.

** Getting started
To get started with ~pentest-env~, clone this repository and run ~vagrant up~ inside the directory.
This will download and run the Kali instance.

You can customize, add targets, create new targets etc.. inside ~pentest-env~.
Some examples are available in the ~examples/~ directory, to use one simply set the ~PENTESTRC~ environment variable:
#+BEGIN_SRC
> PENTESTRC=examples/ctf.pentestrc vagrant status
Current machine states:

kali                      running (virtualbox)
metasploitable            not created (virtualbox)
primer                    not created (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
#+END_SRC

For more details, visit the [[docs/][documentation]] pages:
1. [[docs/Installation.md][Installation]]
2. [[docs/Usage.md][Usage]]
3. [[docs/Docker.md][Docker]]
4. [[docs/Openstack.md][Openstack]]
5. [[docs/Customizations.md][Customizations]]
6. [[docs/Instances.md][Instances]]
7. [[docs/Targets.md][Targets]]
8. [[docs/Custom-instances.md][Write custom instances and targets]]
9. [[docs/Debugging.md][Debugging]]
10. [[docs/About-boxes.md][About boxes]]
11. [[docs/Known-issues.md][Known issues]]

** About Security
**** verify checksums
It's recommended to check downloaded box files with provided checksums (SHA256): http://box.hackbbs.org/checksums.txt
**** sshd is running
Provided boxes run the ~sshd~ service.
So if you plan to run the Kali linux with a Bridged interface, default setup can be dangerous!

- ~root~ password of kali is ~toor~.
- SSH private key is not private! Anyone can use this [[https://github.com/Sliim/pentest-env/blob/master/ssh-keys/pentest-env][key]] to connect to your instance.
- The Kali linux 1.0 box added a ~vagrant~ user with password ~tnargav~ and is in sudoers with no password required.

** License
   See COPYING file
