* Pentest Environment Deployment

This tool provide an easy way to deploy a clean pentesting environment with Kali linux using vagrant and virtualbox.

** Requirements
I assume you are familiar with virtualbox and vagrant.
- https://www.virtualbox.org/
- http://www.vagrantup.com/

Tested with:
- Virtualbox (4.2.10)
- Vagrant (1.0.7)

- Disk space: ~5GB for installation, after installation: ~2.5GB

** Installation
Run:
#+BEGIN_SRC shell
git clone --recursive https://github.com/Sliim/pentest-env.git
cd pentest-env
vagrant up kali
#+END_SRC

If you clone repository not recursively, don't forget to init and update submodules (required for provisionning).

** Box URL
- Kali linux 1.0: http://ftp.sliim-projects.eu/boxes/kali-linux-1.0-amd64.box

** Usage
*** Download and Import Kali linux 1.0 box (optional)
#+BEGIN_SRC shell
wget http://ftp.sliim-projects.eu/boxes/kali-linux-1.0-amd64.box
vagrant box add kali-1.0-amd64 kali-linux-1.0-amd64.box
#+END_SRC
If this part is skipped, vagrant will automatically download box and import it.

*** Running Kali linux 1.0
#+BEGIN_SRC shell
vagrant up kali
#+END_SRC

** About box
Provided box is fresh install of Kali linux 1.0.
 - Some changes was applied:
   + Installation of linux kernel headers for vbox guest additions.
   + Installation of virtualbox guest additions.
   + Installation of ~chef~ package for provisioning.
   + ~vagrant~ user was created for provisionning (Password: ~tnargav~).
   + ~admin~ group don't require password for sudo.
   + ~vagrant~ user is in ~admin~ group.
   + Authorized keys for ~vagrant~ user are stored in ~ssh-keys/~ directory (no passphrase).
   + Enabling rpcbind, nfs-common and ssh services at boot.

If you don't trust me don't use this box !!!

Please don't forget to read security warning below !

** Known issues
*** Hostonly on kali linux 1.0 fail
Hostonly connection will be reset at first vm creation.
To resolve this, disconnect connection in gui mode and run in your vagrant directory:
#+BEGIN_SRC shell
vagrant reload kali
#+END_SRC
** Security warning
Virtual machine boot with sshd service running and may cause some security issues:
  - Bridged network is enabled by default.
  - Everybody know the default root password for Backtrack/Kali distribution.
  - Vagrant user is insecure
    + Private key stored in ~ssh-keys/~.
    + Password known (~tnargav~).
    + User in sudoers with no password required.

So, be careful depending on the network where you are.
You can disable the bridged network in gui mode (inside vm), or comment corresponding line:
#+BEGIN_SRC ruby
#kali.vm.network :bridged, :bridge => "eth0"
#+END_SRC

You can also set up an iptables rule.

** License
   See COPYING file
